version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: guhuzanew_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guhuza_db
      MYSQL_USER: guhuza_user
      MYSQL_PASSWORD: guhuza_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
