version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: guhuzanew_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guhuza_db
      MYSQL_USER: guhuza_user
      MYSQL_PASSWORD: guhuza_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nextjs_app
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://guhuza_user:guhuza_password@mysql:3306/guhuza_db"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["pnpm", "run", "dev"]

volumes:
  mysql_data:
